import React, { useState, useEffect } from "react";
import Head from "next/head";
import axios from "axios";
import Link from "next/link";
import { Icon } from "@iconify/react";

const Done = () => {
  const [todo, setTodo] = useState([]);

  const getDoneTodo = async () => {
    const response = await axios.get("http://localhost:5000/todo/done");
    setTodo(response.data);
    console.log(response.data);
  };

  useEffect(() => {
    getDoneTodo();
    // console.log("welcome");
  }, []);

  const deleteTodo = async (id) => {
    try {
      await axios.delete(`http://localhost:5000/todo/${id}`);
      getDoneTodo(); //refetecher to display new data
    } catch (error) {
      console.log(error);
    }
  };

  const onUndoneTodo = async (item) => {
    try {
      await axios.patch(`http://localhost:5000/todo/${item.id}`, {
        title: item.title,
        description: item.description,
        isDone: false,
      });
      getDoneTodo(); //refetecher to display new data
      //   console.log(item.title);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Simple CRUD user</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-slate-800">
        <div className="flex min-h-screen">
          <div className=" bg-slate-900 flex flex-col fixed w-[25%] h-screen left-0">
            <div className="flex flex-col gap-5 h-[50%] pt-10">
              <div className="text-slate-300 font-mono text-4xl font-bold mx-auto cursor-default h-12 w-[90%] flex items-center justify-center px-5 py-2 rounded-md ">
                Tododo
              </div>
              <Link
                href={"/"}
                className="text-slate-50 text-xl bg-slate-700 cursor-pointer mx-auto h-16 w-[90%] flex items-center justify-center px-5 py-2 rounded-md hover:bg-slate-500"
              >
                <Icon icon="ic:baseline-home" className="mr-1 text-2xl" />
                <span>Home</span>
              </Link>
              <Link
                href={"/done"}
                className="text-slate-50 text-xl bg-slate-500 cursor-pointer mx-auto h-16 w-[90%] flex items-center justify-center px-5 py-2 rounded-md hover:bg-slate-400"
              >
                <Icon
                  icon="ic:baseline-library-add-check"
                  className="mr-1 text-2xl"
                />
                Done
              </Link>
              <Link
                href={"/add"}
                className="text-slate-50 text-xl bg-slate-700 cursor-pointer mx-auto h-16 w-[90%] flex items-center justify-center px-5 py-2 rounded-md hover:bg-slate-500"
              >
                <Icon
                  icon="ic:baseline-add-to-photos"
                  className="mr-1 text-2xl"
                />
                <span>Add new</span>
              </Link>
            </div>
            <div className="flex flex-col gap-5 h-[50%] justify-end pb-10">
              <Link
                href={""}
                className="text-slate-50 text-xl bg-slate-700 mx-auto cursor-pointer h-16 w-[90%] flex items-center justify-center px-5 py-2 rounded-md hover:bg-slate-500"
              >
                <Icon
                  icon="material-symbols:logout"
                  className="mr-1 text-2xl"
                />
                <span>Logout</span>
              </Link>
            </div>
          </div>
          <div className="flex flex-wrap gap-5 p-10 w-[75%] absolute right-0 bg-slate-800">
            {todo.map((item, index) => (
              <div
                className="bg-slate-700 text-slate-50 p-3 shadow-lg flex flex-col rounded-md aspect-square hover:scale-105 duration-300 my-5 relative w-[30%] mx-auto"
                key={item.id}
              >
                <div className="text-xl font-bold">{item.title}</div>
                <div className="text-lg">{item.description}</div>
                <div className="text-rose-500">{`${item.isDone}`}</div>
                <div className="flex absolute gap-1 bottom-3 left-1/2 -translate-x-1/2">
                  <button
                    className="bg-slate-900 py-2 px-3 rounded-xl hover:bg-emerald-400 duration-200 flex items-center justify-center"
                    onClick={() => onUndoneTodo(item)}
                  >
                    <Icon
                      icon="material-symbols:undo"
                      className="mr-1 text-2xl"
                    />
                    Undone
                  </button>
                  <button
                    className="bg-slate-900 py-2 px-3 rounded-xl hover:bg-rose-400 duration-200 flex items-center justify-center"
                    onClick={() => deleteTodo(item.id)}
                  >
                    <Icon
                      icon="material-symbols:delete-sharp"
                      className="mr-1 text-2xl"
                    />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Done;
