import React, { useState, useEffect } from "react";
import Head from "next/head";
import axios from "axios";
import Link from "next/link";

const index = () => {
  const [user, setUser] = useState([]);

  const getUsers = async () => {
    const response = await axios.get("http://localhost:5000/todo");
    setUser(response.data);
    console.log(response.data);
  };

  useEffect(() => {
    getUsers();
    // console.log("welcome");
  }, []);

  const deleteUser = async (id) => {
    try {
      await axios.delete(`http://localhost:5000/users/${id}`);
      getUsers();
    } catch (error) {
      console.log({ deleteUserError: error });
    }
  };

  return (
    <>
      <Head>
        <title>Simple CRUD user</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-orange-100 min-h-screen flex justify-center items-center">
        <div className="relative ">
          <Link
            href={"/add"}
            className="px-4 py-4 bg-emerald-300 text-slate-700 font-bold rounded-lg -top-10  absolute right-0"
          >
            ➕ Add new User
          </Link>
          <table className="table-auto border-2 border-amber-500 mt-5 ">
            <thead className="border-b-2 border-b-amber-500 bg-slate-800 text-white">
              <tr className="">
                <th className="py-3 px-1 text-center">No</th>
                <th className="py-3 px-6">Name</th>
                <th className="py-3 px-6">Email</th>
                <th className="py-3 px-6">Gender</th>
                <th className="py-3 px-1 text-center">Action</th>
              </tr>
            </thead>
            <tbody>
              {user.map((item, index) => (
                <tr
                  className=" odd:bg-emerald-100 even:bg-pink-100"
                  key={item.id}
                >
                  <td className="py-3 px-1 text-center">{index + 1}</td>
                  <td className="py-3 px-6 ">{item.name}</td>
                  <td className="py-3 px-6">{item.email}</td>
                  <td className="py-3 px-6">{item.gender}</td>
                  <td className="py-3 px-1 text-center">
                    <Link
                      href={`/edit/${item.id}`}
                      className="bg-sky-600 hover:opacity-70 text-white px-3 py-2 rounded-md mx-2"
                    >
                      Edit ⚙️
                    </Link>
                    <button
                      className="bg-slate-300 hover:opacity-70  px-3 py-2 rounded-md"
                      onClick={() => deleteUser(item.id)}
                    >
                      Delete ❌
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default index;
